GET http://127.0.0.1:8000/api/transactions/?month=7
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0ODU4ODM5LCJpYXQiOjE3ODQ4NTg1MzksImp0aSI6IjU0ZmM0Y2U3ZjJhZjQ3ZTk4NTc1NGRkZThlYjdjODM3IiwidXNlcl9pZCI6IjYifQ.9VuhwoYIKawiK38uSNU1xB8RikAMaHRK7hGpvLMm7us
Content-Type: application/json

{
    "username": "teste1234",
    "password": "12345678"
}