# Generated by Django 6.0.7 on 2026-07-11 15:35

from django.conf import settings # type: ignore
from django.db import migrations, models # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('user', 'category_name'), name='unique_category_per_user'),
        ),
    ]
